server:
  port: 9000
spring:
  application:
    name: provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123123
    url: mysql://localhost:3306/activiti
# dubbo 配置
dubbo:
  scan:
    base-packages:  com.yyzc.hy.service.impl   #扫描包
  application:
    name: provider     #应用名
  protocol:
    name: dubbo  #用dubbo协议在20880上面暴露服务， 其他应用可以通过该端口调用应用
    port: 20881
    dispatcher: all
    threadpool: fixed
    threads: 10000
  registry:
    address: 192.168.137.2:2181,192.168.137.3:2181,192.168.137.4:2181 #连接注册中心
    protocol: zookeeper
    check: false # 关闭注册中心的接口检查
  provider:
    loadbalance: roundrobin # 服务提供方式，轮训、随机、权重等
    #cache:  lru # 缓存，lru:最近最久不适用， threadlocal：当前线程缓存
    cluster: Failover   # 设置容错机制，failsafe 异常时继续执行
    timeout: 6000 # 提供方 提供全局的的超时时间，单位毫秒
    group:  test
  consumer:
    check: false # 关闭所有接口的启动检查
  monitor:
    protocol: registry





